export const BLOCK_SIZE = 20;
export const PLAYFIELD_BORDER_WIDTH = 2;
export const PLAYFIELD_WIDTH = BLOCK_SIZE * 10 + 2 * PLAYFIELD_BORDER_WIDTH;
export const PLAYFIELD_HEIGHT = 400 + 2 * PLAYFIELD_BORDER_WIDTH;
export const CANVAS_WIDTH = 360;
export const CANVAS_HEIGHT = PLAYFIELD_HEIGHT;
